### ISSUE TITLE
api/rating/productRatingInStore not return ProductId

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-customer-review#24]
Version info: 
- Browser version: 
- Platform version: 3.100.0
- Module version: 3.3.0

### Expected behavior
return product rating and ProductId in route **api/rating/productRatingInStore**

### Actual behavior
not return ProductId

Class return is incorrect, expected RatingProductDto, but return RatingStoreDto

![image](https://user-images.githubusercontent.com/20837564/150767099-3c54a541-0b7e-47be-bab8-0f86371f66ab.png)

![image](https://user-images.githubusercontent.com/20837564/150767254-9b238d38-aa27-473d-be9f-4736a8c06f6c.png)

### Steps to reproduce
1. Call api/rating/productRatingInStore
2.
3.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7903 has been created

**Comment by OlegoO** [comment]
@JoseCaetanoNeto Created PR with the fix https://github.com/VirtoCommerce/vc-module-customer-review/pull/26. 
It's based on .NET 6. [Read release note](https://github.com/VirtoCommerce/vc-platform/blob/dev/docs/release-information/update-to-version-3-200/update-platform-and-modules-to-3-200.md)

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-module-customer-review/releases/tag/3.201.0
