### ISSUE TITLE
Includ rating Count in return API/rating/productRatingInStore and API/rating/productRatingInCatalog

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-customer-review#25]
Currently there is no way to know how many evaluations there were in an optimized way

Includ rating Count in return API/rating/productRatingInStore and API/rating/productRatingInCatalog

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7913 has been created

**Comment by OlegoO** [comment]
@JoseCaetanoNeto Created PR with the fix https://github.com/VirtoCommerce/vc-module-customer-review/pull/26

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-module-customer-review/releases/tag/3.201.0
